### ISSUE TITLE
Add config option to skip local link checks

### ISSUE THREAD

**Issue by saswatamcode** [bwplotka/mdox#87]
We currently can only ignore remote links based on regex, but there are use cases where users might also want to ignore local links.

**Comment by simonpasquier** [comment]
With the prometheus-operator project, we have a use case where it would be handy to disable validation for internal links. The context is https://github.com/prometheus-operator/prometheus-operator/pull/4899 which refactors the generation of the API documentation.

The [resulting MarkDown file](https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/5437e1e5e10a099e2797cf59f8099243b0844c04/Documentation/api.md) is mostly HTML behind the scenes with `<a href="...">` anchor links. As a result, mdox [fails](https://github.com/prometheus-operator/prometheus-operator/runs/7284593923?check_suite_focus=true) validating pages that reference anchor links in the api.md page because it can only process "true" MarkDown syntax.
